previews:
    generation: off

services:
  - name: jdp-chat-room
    type: web
    runtime: docker
    plan: free
    region: oregon
    repo: https://github.com/alecbass/jdp-htmx-chat
    branch: main
    autoDeploy: false
    healthCheckPath: /
    dockerfilePath: ./Dockerfile
    dockerContext: .
    numInstances: 1

envVars:
  - key: API_ADDRESS
    value: 0.0.0.0:8000
  - key: WEBSOCKET_ADDRESS
    value: 0.0.0.0:8001
  - key: WEBSOCKET_CONNECT_URL
    value: wss://jdp-chat-room.onrender.com:8001
