previews:
  generation: off

services:
  - name: jdp-chat-room
    type: web
    runtime: docker
    plan: free
    region: oregon
    repo: https://github.com/alecbass/jdp-htmx-chat
    branch: main
    healthCheckPath: /
    dockerfilePath: ./Dockerfile
    dockerContext: .
    numInstances: 1
